### ISSUE TITLE
Systemd service not created/started

### ISSUE THREAD

**Issue by a0s** [Stouts/Stouts.openvpn#113] opened 2019-01-15 11:39 UTC
Hi,

i have this configuration
```yaml
- hosts: router
  roles: ['Stouts.openvpn']
  vars:
    openvpn_use_pam: no
    openvpn_clients: [scw]
    openvpn_unified_client_profiles: yes
    openvpn_tls_auth: yes
```
It executed without errors, i can see generated scw.ovpn in `/etc/openvpn/keys/`.
But actually it not works
```bash
> ps aux | grep open
root     10118  0.0  0.0  12948   936 pts/0    S+   11:36   0:00 grep --color=auto open
> ss -ln | grep 1194
> systemctl status | grep openvpn
└─10122 grep --color=auto openvpn
```

What i missed? (i don't want use PAM, i need simple connection)

**Comment by nkakouros** [comment] 2019-02-17 12:57
@a0s Do you still have this issue? What OS are you using?

**Comment by a0s** [comment] 2019-02-18 12:16
@tterranigma I think it is still here. I moved to kyl191.openvpn.

**Comment by nkakouros** [comment] 2019-02-18 14:19
OK, closing it as I cannot reproduce it.

**Closed as completed by nkakouros** 2019-02-18 14:19 UTC
Labels: needs info

**Comment by digitalist** [comment] 2019-04-17 17:12
same bug here btw

**Comment by nkakouros** [comment] 2019-04-17 20:26
@digitalist Can you provide some more background information? What distro are you using? Do you have a playbook that can reproduce this?

**Comment by digitalist** [comment] 2019-04-17 21:24
I'll try to reproduce it on a fresh 16.04, but as far as I can tell, there are
a) no openvpn processes visible through `ps ax | grep vpn` 
b) no systemd unit file - just some `want dependency`
c) no log file (guess because openvpn didn't run)

**Comment by digitalist** [comment] 2019-04-17 21:40
I bet it's somewhat related 
![Screenshot at 2019-04-18 00-39-59](https://user-images.githubusercontent.com/3270326/56322761-983fe100-6172-11e9-83ca-a5da22cb1975.png)
